include: package:effective_dart/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
  #- public_member_api_docs //TODO disabled til first release

analyzer:
#   exclude:
#     - path/to/excluded/files/**
