name: soda_db
version: 1.0.0
description: Simple Object-oriented DArt DataBase. SodaDB is a lightweight and simple to use object-oriented storage for Dart and Flutter applications, with type-safe access on entities.
homepage: https://github.com/slumann/soda_db
repository: https://github.com/slumann/soda_db
issue_tracker: https://github.com/slumann/soda_db/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  effective_dart: ^1.1.0
  test: ^1.6.0
  mockito: ^4.1.1
