name: codecov

on: [push]

jobs:
      
  coverage:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Run coverage
        run: |
          pub get
          pub global activate test_coverage
          pub global run test_coverage
      - uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
